---
- name: Install and configure Vector
  hosts: vector:lighthouse
  become: yes
  vars:
    vector_version: "0.34.0"
    vector_download_url: "https://packages.timber.io/vector/0.34.0/vector-0.34.0-x86_64-unknown-linux-gnu.tar.gz"
    vector_install_path: "/usr/local/bin/vector"
    vector_config_file: "/etc/vector/vector.toml"
    vector_user: "vector"
    clickhouse_host: "{{ hostvars['clickhouse-01'].ansible_host }}"
    vector_host: "{{ hostvars['vector-02'].ansible_host }}"

  tasks:
    - name: Ensure Vector user exists
      user:
        name: "vector"
        system: yes
        createhome: no
        shell: /bin/false"

    - name: Ensure necessary directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "vector"
        group: "vector"
        mode: "0755"
      loop:
        - "/var/lib/vector"
        - "/etc/vector"


    - name: Download Vector
      get_url:
        url: "{{ vector_download_url }}"
        dest: "/tmp/vector.tar.gz"

    - name: Extract Vector
      unarchive:
        src: "/tmp/vector.tar.gz"
        dest: "/tmp"
        remote_src: yes
        mode: "0755"

    - name: Move Vector binary to /usr/local/bin
      command: mv /tmp/vector-x86_64-unknown-linux-gnu/bin/vector {{ vector_install_path }}
      args:
        creates: "{{ vector_install_path }}"

    - name: Ensure Vector is executable
      file:
        path: "{{ vector_install_path }}"
        mode: "0755"

    - name: Ensure Vector user exists
      user:
        name: "{{ vector_user }}"
        system: yes
        createhome: no
        shell: /bin/false"



    # ⬇ Устанавливаем конфигурацию ТОЛЬКО для Vector-сервера
    - name: Deploy Vector configuration for Vector Server
      template:
        src: templates/vector_vector.toml.j2
        dest: "{{ vector_config_file }}"
        mode: "0644"
      when: "'vector' in group_names"
      notify: Restart Vector

    # ⬇ Устанавливаем конфигурацию ТОЛЬКО для Lighthouse/Nginx
    - name: Deploy Vector configuration for Lighthouse
      template:
        src: templates/vector_nginx_lighthouse.toml.j2
        dest: "{{ vector_config_file }}"
        mode: "0644"
      when: "'lighthouse' in group_names"
      notify: Restart Vector

    - name: Deploy Vector systemd service file
      copy:
        dest: /etc/systemd/system/vector.service
        content: |
          [Unit]
          Description=Vector service
          After=network.target

          [Service]
          User={{ vector_user }}
          ExecStart={{ vector_install_path }} --config {{ vector_config_file }}
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
      notify: Restart Vector

    - name: Ensure Vector user is in nginx group
      user:
        name: "{{ vector_user }}"
        groups: nginx
        append: yes
      when: "'lighthouse' in group_names"

    - name: Change permissions for Nginx log directory
      file:
        path: /var/log/nginx
        state: directory
        owner: nginx
        group: nginx
        mode: "0755"
      when: "'lighthouse' in group_names"

    - name: Change permissions for Nginx access log
      file:
        path: /var/log/nginx/access.log
        state: file
        owner: nginx
        group: nginx
        mode: "0640"
      when: "'lighthouse' in group_names"

    - name: Change permissions for Nginx error log
      file:
        path: /var/log/nginx/error.log
        state: file
        owner: nginx
        group: nginx
        mode: "0640"
      when: "'lighthouse' in group_names"

    

    - name: Перезапустить systemd для применения изменений
      command: systemctl daemon-reexec

    - name: Enable and start Vector service
      systemd:
        name: vector
        enabled: yes
        state: started
    
    - name: Restart Vector
      systemd:
        name: vector
        state: restarted

    

  handlers:
    - name: Restart Vector
      systemd:
        name: vector
        state: restarted
