---
- name: Install Vector
  get_url:
    url: "https://packages.timber.io/vector/0.34.0/vector-0.34.0-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector.tar.gz"

- name: Extract Vector
  unarchive:
    src: "/tmp/vector.tar.gz"
    dest: "/tmp"
    remote_src: yes
    mode: "0755"

- name: Move Vector binary to /usr/local/bin
  command: mv /tmp/vector-x86_64-unknown-linux-gnu/bin/vector /usr/local/bin/vector
  args:
    creates: /usr/local/bin/vector

- name: Ensure Vector is executable
  file:
    path: "/usr/local/bin/vector"
    mode: "0755"


- name: Ensure Vector user exists
  user:
    name: vector
    system: yes
    createhome: no
    shell: /bin/false

- name: Ensure Vector data directory exists
  file:
    path: "/var/lib/vector/"
    state: directory
    owner: vector
    group: vector
    mode: "0755"
    
- name: Ensure Vector configuration directory exists
  file:
    path: "/etc/vector"
    state: directory
    mode: "0755"

- name: Ensure Vector data directory exists
  file:
    path: "/var/lib/vector/"
    state: directory
    owner: vector
    group: vector
    mode: "0755"


- name: Deploy Vector configuration from template
  template:
    src: vector.toml.j2
    dest: "/etc/vector/vector.toml"
    mode: "0644"
  notify: Restart Vector

- name: Create systemd service for Vector
  copy:
    dest: "/etc/systemd/system/vector.service"
    content: |
      [Unit]
      Description=Vector Service
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/vector --config /etc/vector/vector.toml
      Restart=always
      User=root

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start and enable Vector service
  systemd:
    name: vector
    enabled: true
    state: started
